[environments]
  [environments.development]
    name = "web"
    namespace = "default"
    wait = false
    watch = false
    watch-delay = 1
    auto-connect = false
    override-ports = ["3000:3000"]

